title: "drop"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
search_enabled: true
logo: "/assets/logo.png"
plugins:
  - jekyll-seo-tag
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "drop8k"
